# Generated by Django 4.1.7 on 2023-02-17 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('departamento_name', models.CharField(max_length=30, verbose_name='Departamento')),
                ('countries_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.countries', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='distrito',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('distrito_name', models.CharField(max_length=70, verbose_name='Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_name', models.CharField(max_length=30, verbose_name='Documento')),
                ('countries_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.countries', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('empresa_name', models.CharField(max_length=40, verbose_name='Razon Social')),
                ('direccion_name', models.CharField(max_length=50, verbose_name='Direccion')),
                ('departamento', smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='countries_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.departamento')),
                ('distrito', smart_selects.db_fields.ChainedForeignKey(chained_field='provincia', chained_model_field='provincia_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.distrito')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.countries', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_name', models.CharField(max_length=30, verbose_name='Horario')),
                ('horario_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('horario_salida', models.TimeField(verbose_name='Hora de salida')),
                ('horario_tolerancia', models.SmallIntegerField(verbose_name='Tiempo de tolerancia')),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('provincia_name', models.CharField(max_length=70, verbose_name='Provincia')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=30, verbose_name='Local')),
                ('local_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('departamento', smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='countries_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.departamento')),
                ('distrito', smart_selects.db_fields.ChainedForeignKey(chained_field='provincia', chained_model_field='provincia_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.distrito')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.empresa', verbose_name='Empresa')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.countries', verbose_name='Pais')),
                ('provincia', smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.provincia'),
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('empleado_telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('empleado_nrodocumento', models.CharField(max_length=12, verbose_name='Numero de documento')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.area', verbose_name='Area')),
                ('departamento', smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='countries_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.departamento')),
                ('distrito', smart_selects.db_fields.ChainedForeignKey(chained_field='provincia', chained_model_field='provincia_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.distrito')),
                ('documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.documento', verbose_name='Tipo de documento')),
                ('horario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.horario', verbose_name='Horario')),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.local', verbose_name='Local')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.countries', verbose_name='Pais')),
                ('provincia', smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento_id', on_delete=django.db.models.deletion.CASCADE, to='asistencia.provincia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.provincia', verbose_name='Provincia'),
        ),
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.empresa', verbose_name='Empresa'),
        ),
    ]
